@startuml クラス図 2

'クラスのアイコン表示をやめる
hide circle

package "パッケージは package" #DDDDDD {
  interface リストインターフェース <<interface>>{
    string[] GetList()
  }
  
  abstract class 抽象リストクラス{
    string[] GetList()
  }

  class 具象リストクラス {
    Object[] elementData
    size()
    string[] GetList()
  }

  リストインターフェース <|-- 抽象リストクラス
  抽象リストクラス <|-- 具象リストクラス
}

namespace 名前空間はnamespace #DDDDDD {
	.BaseClass <|-- Person
	Meeting o-- Person
	
	.BaseClass <|- Meeting
}

@enduml