hoge

fuga

Function Func1()
WriteLogSimple "test3.cls" & vbTab & "Func1" & vbTab & "START"  'for DEBUG
WriteLogSimple "test3.cls" & vbTab & "Func1" & vbTab & "END"  'for DEBUG
End Function

Private Function Func2()
WriteLogSimple "test3.cls" & vbTab & "Func2" & vbTab & "START"  'for DEBUG
WriteLogSimple "test3.cls" & vbTab & "Func2" & vbTab & "END"  'for DEBUG
End Function

Public Function Func3()
WriteLogSimple "test3.cls" & vbTab & "Func3" & vbTab & "START"  'for DEBUG
WriteLogSimple "test3.cls" & vbTab & "Func3" & vbTab & "END"  'for DEBUG
End Function

Public Function Func4(ByVal arg As String)
WriteLogSimple "test3.cls" & vbTab & "Func4" & vbTab & "START"  'for DEBUG
WriteLogSimple "test3.cls" & vbTab & "Func4" & vbTab & "END"  'for DEBUG
End Function

Public Function Func5(arg As String)
WriteLogSimple "test3.cls" & vbTab & "Func5" & vbTab & "START"  'for DEBUG
WriteLogSimple "test3.cls" & vbTab & "Func5" & vbTab & "END"  'for DEBUG
End Function

Public Function Func6(arg)
WriteLogSimple "test3.cls" & vbTab & "Func6" & vbTab & "START"  'for DEBUG
WriteLogSimple "test3.cls" & vbTab & "Func6" & vbTab & "END"  'for DEBUG
End Function



