hoge

fuga

Function Func1()
WriteLogSimple "test3.cls:Func1 START"  'for DEBUG
WriteLogSimple "test3.cls:Func1 END"  'for DEBUG
End Function

Private Function Func2()
WriteLogSimple "test3.cls:Func2 START"  'for DEBUG
WriteLogSimple "test3.cls:Func2 END"  'for DEBUG
End Function

Public Function Func3()
WriteLogSimple "test3.cls:Func3 START"  'for DEBUG
WriteLogSimple "test3.cls:Func3 END"  'for DEBUG
End Function

Public Function Func4(ByVal arg As String)
WriteLogSimple "test3.cls:Func4 START"  'for DEBUG
WriteLogSimple "test3.cls:Func4 END"  'for DEBUG
End Function

Public Function Func5(arg As String)
WriteLogSimple "test3.cls:Func5 START"  'for DEBUG
WriteLogSimple "test3.cls:Func5 END"  'for DEBUG
End Function

Public Function Func6(arg)
WriteLogSimple "test3.cls:Func6 START"  'for DEBUG
WriteLogSimple "test3.cls:Func6 END"  'for DEBUG
End Function



