
hoge

fuga

Function Func1()
WriteLogSimple "Func1 START"  'for DEBUG
WriteLogSimple "Func1 END"  'for DEBUG
End Function

Private Function Func2()
WriteLogSimple "Func2 START"  'for DEBUG
WriteLogSimple "Func2 END"  'for DEBUG
End Function

Public Function Func3()
WriteLogSimple "Func3 START"  'for DEBUG
WriteLogSimple "Func3 END"  'for DEBUG
End Function

Public Function Func4(ByVal arg As String)
WriteLogSimple "Func4 START"  'for DEBUG
WriteLogSimple "Func4 END"  'for DEBUG
End Function

Public Function Func5(arg As String)
WriteLogSimple "Func5 START"  'for DEBUG
WriteLogSimple "Func5 END"  'for DEBUG
End Function

Public Function Func6(arg)
WriteLogSimple "Func6 START"  'for DEBUG
WriteLogSimple "Func6 END"  'for DEBUG
End Function



