@startuml コンポーネント図 1

'コメント

title タイトルは title\n改行は\\n

'基本
[コンポーネントは括弧。エイリアスはas] as C1
() "インターフェースは()" as I1

'------------------------------------
[コンポ2]  as C2 #Blue

package "パッケージは package"{
  [コンポ3] as C3 #008833
  [コンポ4] as C4
}

() "データアクセス" as DA
() "HTTP" as HTTP

'------------------------------------
'破線 (..)、直線 (--), 矢印 (-->) 

C2 - DA : 横の実線は -
DA -- HTTP : 縦の実線は --
HTTP -> C3 : 横の矢印は ->
C3 ..> C4 : 縦の破線は ..>

note left of C4 : 注釈（左）は note left of XXX

@enduml